permalink: /blog/:year/:month/:day/:title
markdown: kramdown
baseurl: ""
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
# Uncomment below for local testing. It will build much faster since it doesn't have to look through all those directories.
# exclude: [apps, built-apps, node_modules, packages, ui]
